version: '3.3'
services:
  
  master:
    container_name: master
    build:
#      user: root
      context: ./
      dockerfile: ./Dockerfile
    command: ./master
    tty: true
    stdin_open: true

  server:
    container_name: server
    build:
#      user: root
      context: ./
      dockerfile: ./Dockerfile
    command: ./slave